### ISSUE TITLE
how to hide the navigator?

### ISSUE THREAD

**Issue by yihui** [brentertz/scianimator#1]
according to the introduction in README, it seems we can hide the navigator using the option `'controls': ['first', 'previous', 'play', 'next', 'last', 'loopMode', 'speed']`, but when I did this, the whole controls disappeared...

BTW, thanks for the great job! I like it very much!

**Comment by brentertz** [comment]
In your controls array, 'loopMode' should be 'loop'.  The docs were wrong.  Updating now...

**Comment by yihui** [comment]
awesome! it works now
