### ISSUE TITLE
the animation "jumps" over certain frames when 'delay' is small

### ISSUE THREAD

**Issue by yihui** [brentertz/scianimator#2]
say, when delay = 50, the animation will jump over a certain number of image frames and make the animation not "continuous" (tested under Firefox 3.6.13)

can this problem be fixed? 

(you can test with your examples on the homepage: http://brentertz.github.com/scianimator/ simply increase the speed to the maximum; besides, it is difficult to stop the animation when `delay` is small -- the stop button will not respond)

**Comment by brentertz** [comment]
Interesting find - thanks for posting.  The frames are not actually being skipped however.  Turn debug on and see that each frame appears in proper order in the console log.

I feel that the behavior may be in part dependent on how robust the client system is.  That being said, I would suggest that you turn debug off and give it a try too, as the debug setting will surely affect performance.  Also, close Firebug if you have it open and see if that improves the situation.  Taking these steps likewise resolved the non-responsive stop button for me.

Further, if the previous suggestions do not resolve your issue, I might suggest to increase the value of 'delayMin' to something more reasonable for your situation - perhaps 100ms.  The default of 25ms is pretty darn fast, and it seems that some browsers/systems may not be able to keep up.

**Comment by yihui** [comment]
Thanks! You suggestions are very helpful!

I've tested it again, and found that the navigator panel might be the main cause for the poor performance. If I don't use the navigator, I can increase the speed up to 0ms.
