### ISSUE TITLE
IE, IE... the evil IE...

### ISSUE THREAD

**Issue by yihui** [brentertz/scianimator#3]
Hi Brent,

Today I tried to use your JS library in my Dokuwiki plugin to create animations, and I succeeded in almost all browsers except IE (I'm testing with IE8). I spent several hours on debugging the script but still have no luck. Could you take a look at my problem when you are free? Here is an example page:

http://animation.yihui.name/prob:flipping_coins

I added `jQuery.noConflict();` to the page because Dokuwiki has an internal JS function `$`.

I used `"shCore.js"`,`"shAutoloader.js"`,`"shBrushR.js"` to highlight the code, but these scripts should not affect SciAnimator either. I did try to turn them off and the animation still would not show up in IE8.

Thanks very much!

**Comment by yihui** [comment]
FYI, IE9 works fine, so it might be due to the canvas script.

**Comment by brentertz** [comment]
This seems to be an issue related to the excanvas script as you suggest.  I have no solution just yet as I am already inserting the canvas into the page before attempting to initialize it with G_vmlCanvasManager, as excanvas recommends.  I'll test more this week...

**Comment by yihui** [comment]
OK, thanks!

**Comment by brentertz** [comment]
Yay, I've got a fix for you.  It is an easy one too.  I simply had to ensure that the canvas element was being rendered as a block element.  Grab an updated `scianimator.css` file and you should be good to go.  Alternatively, you can just add the following to your current file.
`
.scianimator canvas {
  display: block;
}
`

**Comment by yihui** [comment]
Great! Thanks so much!
