### ISSUE TITLE
Is it possible to automatically detect the width and height of images?

### ISSUE THREAD

**Issue by yihui** [brentertz/scianimator#4]
Sometimes I wish I could leave the width/height options empty, and let the canvas fit the images automatically... Is this possible?

**Comment by brentertz** [comment]
Do you mean that images should scale to fit the canvas, or that the canvas should scale to fit the image?

**Comment by yihui** [comment]
the latter -- don't scale the images

**Comment by brentertz** [comment]
Please have a look at the updates in version 1.4.  If you now leave out the width (and height) properties, I believe that you will get the desired behavior. Note that you will need to update your scripts and CSS to the latest version.

**Comment by yihui** [comment]
Great! I'll try later. Thanks so much!

**Comment by yihui** [comment]
If the width is undefined, the canvas will span to a maximumly possible width; this might be desirable -- can its width just fit with the images? The calculated width can be obtained by `$(#any_loaded_image).width()`, right?

**Comment by brentertz** [comment]
I believe that the current implementation is likely the more expected/desirable behavior.  However, you can likely just tweak your CSS to achieve the behavior that you are after. 

Try this...  Do not set a width in SciAnimator.  Modify your CSS and add a `display: inline-block` to your SciAnimator element.

For example:
<code>#MyAnimatorElement { display: inline-block; } </code>

**Comment by yihui** [comment]
Awesome! This works for me. Thanks!

I said spanning was not desirable because I believe it is very rare for users to put images inside a too wide canvas. Usually we just want the images and the "animation player" to fit each other.

**Comment by brentertz** [comment]
Great - glad to hear it.
